project_id = "yvclpmdgrwugayrvjtqg"

[functions.analyze-trade]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = true

[functions.trade-chat]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = true

[functions.telegram-weekly-summary]
verify_jwt = false